### ISSUE TITLE
CMS: 2015 global tags

### ISSUE THREAD

**Issue by katilp** [cernopendata/data-curation#103]
The global tags needed for 2015 are
- 76X_dataRun2_16Dec2015_v0 for data
- 76X_mcRun2_asymptotic_RunIIFall15DR76_v1 for MC

(see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideFrontierConditions#Global_Tags_for_RunIIFall15DR76)

The run range for certified 2015 data at PromptReco level is:

246909 - 26027

see https://twiki.cern.ch/twiki/bin/viewauth/CMS/PdmV2015Analysis#ReReco_for_25_ns and
Cert_246908-260627_13TeV_PromptReco_Collisions15_25ns_JSON_v2.txt

This includes 0 T runs 246908 -250902 (0 T)
(see https://twiki.cern.ch/twiki/bin/view/CMS/CertificationResults2015#JSON_files) 

0 T datasets are not part of the release, but as they've been processed with the same GTs, it would be good to "include" their run range when getting the GT (whether that matters).

The reprocessed certified range starts at a later run (magnet on) and extends to 260627 (#104)

**Comment by katilp** [comment]
@ggovi (and FYI @clelange): Would you kindly extract the condition data for 2015 and make the file available in /cvmfs/cms-opendata-conddb.cern.ch:
- CMSSW_7_6_7
- run range: 246909 - 26027
- Data: 76X_dataRun2_16Dec2015_v0
- MC: 76X_mcRun2_asymptotic_RunIIFall15DR76_v1

Note that for the earlier Run-2 GTs (for some data science MC samples), we ended having to set `process.GlobalTag.snapshotTime = cms.string("9999-12-31 23:59:59.000")` when using them, see in http://opendata.cern.ch/docs/cms-guide-for-condition-database

For the record, for the upload:

> login to cvmfs-cms-opendata-conddb.cern.ch and then do
> 
> ```
> sudo -i -u cvcmso
> cvmfs_server transaction cms-opendata-conddb.cern.ch
> 
> Now /cvmfs/cms-opendata-conddb.cern.ch is writable and you can use the
> shell to copy all the files you need. Once finished, you'd do
> 
> cvmfs_server publish cms-opendata-conddb.cern.ch
> 
> And ~1h later the content appears at the clients.
> 
> ```

**Comment by ggovi** [comment]
@katilp 
"run range: 246909 - 26027": perhaps there is a missing char in the upper limit...?

**Comment by katilp** [comment]
@ggovi Yes, you're right: should be  260627. Now corrected also above. Thanks!

**Comment by ggovi** [comment]
I have executed the two exports as follows:

conddb copy 76X_dataRun2_16Dec2015_v0 --destdb 76X_dataRun2_16Dec2015_v0.db -f 246909 -t 260627
conddb copy 76X_mcRun2_asymptotic_RunIIFall15DR76_v1 --destdb 76X_mcRun2_asymptotic_RunIIFall15DR76_v1.db

To publish in /cvmfs I've used the above recipe. Here is the outcome:

[govi@lxplus790 public]$ ls -l /cvmfs/cms-opendata-conddb.cern.ch/76*
-rwxr-xr-x. 1 cvmfs cvmfs 1171038208 Oct  4 10:54 /cvmfs/cms-opendata-conddb.cern.ch/76X_dataRun2_16Dec2015_v0.db
-rwxr-xr-x. 1 cvmfs cvmfs  674693120 Oct  4 10:56 /cvmfs/cms-opendata-conddb.cern.ch/76X_mcRun2_asymptotic_RunIIFall15DR76_v1.db

Waiting from feedback from the processing...

**Comment by katilp** [comment]
Thanks a lot @ggovi !
I'll test and let you know.
