### ISSUE TITLE
CMS: add 2015 HI ppref collision dataset description CSV file

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/data-curation#165]
Add the usual dataset descriptions CSV file to `cms-2015-collision-datasets-hi-ppref`.

Example:  `cms-2015-collision-datasets/inputs/CMSDatasetDescription_Run2015D.csv`

@katilp Would you have the HI ppref dataset descriptions ready already?

**Comment by katilp** [comment]
Not yet, I'll need to confirm with the HI conveners.
