### ISSUE TITLE
CMS: testing HI GT

### ISSUE THREAD

**Issue by katilp** [cernopendata/data-curation#174]
From #144

Testing reading of HI GT from /cvmfs

GR_P_V43D
STARTHI53_LV1

look OK based on tests using configs from `CMSSW_5_3_20/src/HeavyIonsAnalysis/JetAnalysis/test/`

For STARTHI53_V27 problems related to **L1GtStableParametersRcd**

For STARTHI53_V28 observing this related to **L1GtPrescaleFactorsAlgoTrigRcd**:

The db are there:

```
[root@od-vm ~]# ls /cvmfs/cms-opendata-conddb.cern.ch/STARTHI53_V28 | grep L1GtPrescale
L1GtPrescaleFactorsAlgoTrig_STARTUP_v3.db
L1GtPrescaleFactorsTechTrig_STARTUP_v3.db
```

```
[root@od-vm ~]# ls /cvmfs/cms-opendata-conddb.cern.ch/STARTHI53_V27 | grep L1GtStable
L1GtStableParameters_STARTUP_v3.db
```

so not clear why the error message is different. The input file is the same

**Comment by katilp** [comment]
This was with an input file
root://eospublic.cern.ch//eos/opendata/cms/himc/HiWinter13/QCD_Pt_50_TuneZ2_2p76TeV_pythia6/GEN-SIM-RECO/STARTHI53_V28-v1/00000/0026CFBA-687A-E311-BDCE-848F69FD29BE.root

Change to 
root://eospublic.cern.ch//eos/opendata/cms/himc/HiWinter13/Pythia_AllQCDPhotons_PtHat120_TuneZ2_cmssw53p14_2760GeV/GEN-SIM-RECO/STARTHI53_V28-v1/00000/0EAF7847-899B-E311-AC57-F04DA275BFFB.root

With this file, the job runs without errors with the GT from frontier but fails with the same error when reading from cvmfs:

```
 Beginning HLTBitAnalyzer Analysis
----- Begin Fatal Exception 19-Jul-2023 10:08:00 CEST-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing run: 1
   [1] Running path 'hltAna'
   [2] Calling beginRun for module HLTBitAnalyzer/'hltanalysis'
Exception Message:
No "L1GtPrescaleFactorsAlgoTrigRcd" record found in the EventSetup.
 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------

```

**Comment by katilp** [comment]
Comparing "index" db files from `/cvmfs/cms-opendata-conddb`

```
sqlite3 /cvmfs/cms-opendata-conddb.cern.ch/STARTHI53_LV1.db .dump > indexlv1.txt
sqlite3 /cvmfs/cms-opendata-conddb.cern.ch/STARTHI53_V27.db .dump > indexv27.txt
```

NB an index shift:

V27 - with problems: starts with **2**

```
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE TAGINVENTORY_TABLE (tagname TEXT NOT NULL, objectname TEXT NOT NULL, recordname TEXT NOT NULL, tagid ULONGLONG PRIMARY KEY, pfn TEXT NOT NULL, labelname TEXT);
INSERT INTO "TAGINVENTORY_TABLE" VALUES('SiStripBadModule_Ideal_31X_v2','SiStripBadStrip','SiStripBadModuleRcd',2,'sqlite_file:./STARTHI53_V27/SiStripBadModule_Ideal_31X_v2.db','');
INSERT INTO "TAGINVENTORY_TABLE" VALUES('L1CaloHcalScale_EEG_EHSUMS_TAU4_FGNOHOE_CALIBV1_09JAN13_mc','L1CaloHcalScale','L1CaloHcalScaleRcd',3,'sqlite_file:./STARTHI53_V27/L1CaloHcalScale_EEG_EHSUMS_TAU4_FGNOHOE_CALIBV1_09JAN13_mc.db','');
[ ... ]
CREATE TABLE "TAGTREE_TABLE_STARTHI53_V27" ( "lft" ULONGLONG NOT NULL,"globaltill" ULONGLONG ,"rgt" ULONGLONG NOT NULL,"nodelabel" TEXT NOT NULL,"tagid" ULONGLONG ,"parentid" ULONGLONG NOT NULL,"nodeid" ULONGLONG ,"globalsince" ULONGLONG , PRIMARY KEY("nodeid"), UNIQUE ( "nodelabel" ) );
INSERT INTO "TAGTREE_TABLE_STARTHI53_V27" VALUES(1,4294967295,306,'Calibration',0,0,1,0);
INSERT INTO "TAGTREE_TABLE_STARTHI53_V27" VALUES(2,0,305,'All',0,1,2,0);

```

LV1 (works): starts with **1**

```
-bash-4.2$ head indexlv1.txt
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE "TAGINVENTORY_TABLE" ( "tagname" TEXT  NOT NULL,"objectname" TEXT  NOT NULL,"recordname" TEXT  NOT NULL,"tagid" ULONGLONG ,"pfn" TEXT  NOT NULL,"labelname" TEXT , PRIMARY KEY("tagid") );
INSERT INTO "TAGINVENTORY_TABLE" VALUES('HcalFlagHFDigiTimeParams_v1.0_mc','HcalFlagHFDigiTimeParams','HcalFlagHFDigiTimeParamsRcd',1,'sqlite_file:./STARTHI53_LV1/HcalFlagHFDigiTimeParams_v1.0_mc.db','');
[ ... ]
CREATE TABLE "TAGTREE_TABLE_STARTHI53_LV1" ( "lft" ULONGLONG  NOT NULL,"globaltill" ULONGLONG ,"rgt" ULONGLONG  NOT NULL,"nodelabel" TEXT  NOT NULL,"tagid" ULONGLONG ,"parentid" ULONGLONG  NOT NULL,"nodeid" ULONGLONG ,"globalsince" ULONGLONG , PRIMARY KEY("nodeid"), UNIQUE ( "nodelabel" ) );
INSERT INTO "TAGTREE_TABLE_STARTHI53_LV1" VALUES(1,4294967295,576,'All',0,0,1,0);
INSERT INTO "TAGTREE_TABLE_STARTHI53_LV1" VALUES(2,0,575,'Calibration',0,1,2,0);
```

**Comment by katilp** [comment]
Testing on VM, see https://github.com/cernopendata/opendata.cern.ch/issues/3397#issuecomment-1653733431

The "override" functions in CommonFunctions_cff.py for [5_3_20](https://github.com/CmsHI/cmssw/blob/forest_CMSSW_5_3_20/HeavyIonsAnalysis/Configuration/python/CommonFunctions_cff.py) and [7_5_8_pattch3](https://github.com/CmsHI/cmssw/blob/forest_CMSSW_7_5_8_patch3/HeavyIonsAnalysis/Configuration/python/CommonFunctions_cff.py) read the db tags directly from the condition db (not from the GT).

These separated db's have now been added to

```
/cvmfs/cms-opendata-conddb.cern.ch/hi_53_add_ons/
/cvmfs/cms-opendata-conddb.cern.ch/hi_75_add_ons/
```
and they can be accessed with a modified CommonFunctions_cff.py.

For ease of use, a repository with the modified config files and this file should be added under https://github.com/orgs/cms-opendata-validation/

**Comment by clelange** [comment]
Should be fixed by https://gitlab.cern.ch/cms-opendata/cms-opendata-releaseguide/-/merge_requests/39

Also updated `STARTHI53_V27.db` and `STARTHI53_V28.db` in `/cvmfs/cms-opendata-conddb.cern.ch/`.
