### ISSUE TITLE
CMS - add creation of NanoAOD content documentation to NanoAOD scripts 

### ISSUE THREAD

**Issue by katilp** [cernopendata/data-curation#213]
Add a step to generate the NanoAOD automated docs for NanoAOD datasets
Include it in the scripts for
- 2016 collision #177
- 2016 MC #207 
- PFNano, see #212 

@jmhogan Can you point to the script to generate the docs? Found it:
This: https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/test/inspectNanoFile.py
Usage:
```
python3 inspectNanoFile.py --doc <name>.html <input nano root file>
```

and in json

```
python3 inspectNanoFile.py --json <name>.html  <input nano root file>
```

(NB the json contains also numerical values for the contents of the input file, and the HTML only the documentation)

Example:
[doc.json](https://github.com/cernopendata/data-curation/files/13325082/doc.json)

**Comment by katilp** [comment]
This works only for PFNano and normal Nano.

For NanoAODRun1 this is provided
https://github.com/cms-opendata-analyses/NanoAODRun1ProducerTool/blob/main/tools/documentation.py

but it gives an error:


```
[kati@lxplus911 src]$ python3 ~/documentation.py --doc test.html /eos/opendata/cms/derived-data/POET/23-Jul-22/Run2015D_SingleMuon/FE12438A-4311-4319-97FA-9C2216976C53.root
Traceback (most recent call last):
  File "/afs/cern.ch/user/k/kati/documentation.py", line 332, in <module>
    filedata = FileData(inspectRootFile(args[0]))
  File "/afs/cern.ch/user/k/kati/documentation.py", line 102, in inspectRootFile
    entries = tree.GetEntries()
AttributeError: 'TObject' object has no attribute 'GetEntries'
```

(plain lxplus, new OS - `inspectNanoFile.py` on PFNano works there)

**Comment by tpmccauley** [comment]
Done
