### ISSUE TITLE
Fix hard coded title 'conffile' for cms-YYYY-simulated-datasets

### ISSUE THREAD

**Issue by mantasavas** [cernopendata/data-curation#28]
Using similar approach as in   `data-curation/cms-2011-simulated-datasets/code/create_config_file_records.py`:

```
def get_title(afile):
    "Return suitable title of configuration file."
    return 'Configuration file for ' + get_process(afile) + ' step ' + get_python_filename(afile)
```

title should carry some meaning and be generated dynamically and not hard coded as it's now in `data-curation/cms-YYYY-simulated-datasets/code/dataset_records.py`:

```console
$ git grep conffile
dataset_records.py:236:            configuration_files['title'] = 'conffile'
```

**Comment by tiborsimko** [comment]
(stems from https://github.com/cernopendata/opendata.cern.ch/pull/2527#discussion_r268590550)

**Comment by tiborsimko** [comment]
The commended line changed in the meantime alongside the handling of steps, production scripts, and generator parameters. We now use CMS ConfDB ID to link to configuration files stored on EOSPUBLIC.  The file title guessing WRT steps is not fully necessary as per the new display for MC records.
