### ISSUE TITLE
records: fix created date methodology description

### ISSUE THREAD

**Issue by mantasavas** [cernopendata/data-curation#38]
Script needs some fixes:
* created_date should be an array
* methodology description should be: "These data were generated in several steps (see also CMS Monte Carlo Production Overview)"
* cmsdriver script should be: "Production script"

**Comment by katilp** [comment]
@mantasavas From what we had, it is "cmsdriver script" that should become "Production script" (in case they were mixed later, i.e. production script title somehow became "configuration file" and I have not followed, pls ignore this)

**Comment by tiborsimko** [comment]
@katilp Yes, it is cmsDriver that needs to be changed, the description of the issue is not correct, but the PR is :wink:

**Comment by mantasavas** [comment]
Thank you for noticing!
