### ISSUE TITLE
CMS: a script to extract configurations for data taking

### ISSUE THREAD

**Issue by katilp** [cernopendata/data-curation#67]
All configuration files used in data taking of CMS data are stored and made available as [COPD records](http://opendata.cern.ch/search?page=1&size=20&q=&subtype=Configuration%20HLT&type=Supplementaries) 

The configurations are listed in
- https://fwyzard.web.cern.ch/fwyzard/hlt/2010/summary
- https://fwyzard.web.cern.ch/fwyzard/hlt/2011/summary
- https://fwyzard.web.cern.ch/fwyzard/hlt/2012/summary
- https://fwyzard.web.cern.ch/fwyzard/hlt/2015/summary
- https://fwyzard.web.cern.ch/fwyzard/hlt/2016/summary
- https://fwyzard.web.cern.ch/fwyzard/hlt/2017/summary
- https://fwyzard.web.cern.ch/fwyzard/hlt/2018/summary

Summary pages based on the information of listings above are provided for each year of data taking:
- 2010: http://opendata.cern.ch/record/1699
- 2011: http://opendata.cern.ch/record/1700
- 2012: http://opendata.cern.ch/record/1701

The configuration files have been extracted manually from https://cmsweb.cern.ch/confdb/

Write a script to extract the configuration files for Run2 data taking.

The CODP summary pages show only the data-taking periods which are open data even if all config files will be extracted. 2015 open data will be RunD,  see #70 run numbers
Minimum: 256630
Maximum: 260627

**Comment by katilp** [comment]
A query example 

`python HLTrigger/Configuration/python/Tools/confdbOfflineConverter.py --configName /cdaq/physics/Run2015/25ns14e33/v3.3/HLT/V3 --adg > hltMenu_2015_v3p3.py
`
Need to be in a relatively recent release, ie >= 10_6_3 as the database hosts changed.

**Comment by katilp** [comment]
@tiborsimko where would you like to have the config files stored for Run2 data-takings years? Should we create /eos/opendata/cms/configuration-files/2015 to start with (or use some temporary area)?

**Comment by tiborsimko** [comment]
Usually it is stored locally in data-curation caches, until the time we have the list of datasets and their provenance nailed down, and then it is copied over to the EOS location indeed.

**Comment by katilp** [comment]
This script (and what follows #74) can go in a new directory named `cms-run2-hlt-triggers` with a similar structure as cms-2011-hlt-triggers i.e. two subdirectories: `code` and `inputs`

**Comment by mokotus** [comment]
Will be integrated together with #74, closing for now
