### ISSUE TITLE
CMS: provenance metadata for 2015 MC

### ISSUE THREAD

**Issue by katilp** [cernopendata/data-curation#68]
(from #65)

Run2 legacy metadata of 2016-2018 will be extracted from the ultra-legacy production, see https://github.com/cernopendata/data-curation/tree/master/cms-run2-ultra-legacy-production.

Run1 metadata has been extracted with 
- https://github.com/cernopendata/data-curation/tree/master/cms-2010-simulated-datasets
- https://github.com/cernopendata/data-curation/tree/master/cms-2011-simulated-datasets
- https://github.com/cernopendata/data-curation/tree/master/cms-2012-simulated-datasets

2015 is a separate production and the script may need to be modified.

Run2 Fall15 MiniAOD v2 campaign (76X version 2)[`dataset=/*/*RunIIFall15MiniAODv2-PU25nsData2015v1*/*`](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2F*%2F*RunIIFall15MiniAODv2-PU25nsData2015v1*%2F*)
Size: 227.4TB
7114 datasets

Check if the 2015 MC extraction works with the ultra-legacy script, or if the previous Run1 scripts should be used. 

Run the script and prepare the records.

**Comment by katilp** [comment]
NB that for Run1, the datasets are in AODSIM format, but for Run2 they will be in MiniAODSIM, which is an additional step in the production chain, which was not present during Run1.
See [an example of a MiniAODSIM dataset](http://opendata.cern.ch/record/12015) that has been released in the context of ML sample release July 2019. The outcome of the script should be like that.

**Comment by katilp** [comment]
Because of the features in 2015 MC production, some McM entries do not have the input data field filled although it is available in DAS.

The script in https://github.com/cernopendata/data-curation/tree/master/cms-YYYY-simulated-datasets for all further provenance extractions. The query logic (parent relationship from DAS), should not be modified for 2015, but can be done for UL afterwards.

To test:
- Make a short CMS-0000-mc-datasets.txt in input
- Go to bash
- `voms-proxy-init --voms cms --rfc --valid 190:00`
- Edit script to give no-create-eos-indexes and input to the first step
- go to python3 e.g. with `source /afs/cern.ch/user/r/reana/public/reana/bin/activate` and check python version with `python -V`
- Run `YYYY=0000 ./make_local_cache.sh`

To do:
- comment out the config extraction, and check in how many cases input data is not available in McM if running through all files.

**Comment by katilp** [comment]
- https://opendata-qa.cern.ch/record/15333 - step HLT RECO information missing:
  ```
  Step
  Release: CMSSW_7_6_1
  Output dataset: /AToZhToLLTauTau_M-260_13TeV_madgraph_4f_LO/RunIIFall15DR76-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/AODSIM
  ```
- https://opendata-qa.cern.ch/record/16770 - step HLT RECO information missing
  ```
  Step
  Release: CMSSW_7_6_1
  Output dataset: /GG_M-2000To4000_Pt-70_13TeV-sherpa/RunIIFall15DR76-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/AODSIM
  ```
- https://opendata-qa.cern.ch/record/21714
  ```
  Step
  Release: CMSSW_7_6_3
  Output dataset: /ZprimeToA0hToA0chichihZZTo4l_2HDM_MZp-1400_MA0-300_13TeV-madgraph-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v2/MINIAODSIM
  ```

**Comment by katilp** [comment]
The missing 5 config are in `/eos/opendata/cms/upload/kati/addedconfigs` ready to be move under `/eos/opendata/cms/configuration-files/MonteCarlo2015`

**Comment by tiborsimko** [comment]
The 5 files are already in the target location, for example:

```
/eos/opendata/cms/configuration-files/MonteCarlo2015/1afa7fc4132ca1afecdba4b11c0d3b18.configFile.py
```
