### ISSUE TITLE
CMS - HI transfers

### ISSUE THREAD

**Issue by katilp** [cernopendata/data-curation#73]
(from #72 )

## I: 2010-2011 slc5-based HI samples 
Information provided by HI conveners, see also [the detailed table](https://docs.google.com/spreadsheets/d/18TCtxtMYN_KmLIDhfoGB5m1prmgh6_WtKEudej3s56E/edit#gid=0) by HI conveners 

Transfers started indicated with a tick box, ongoing **bold**

### 2010 PbPb slc5, CMSSW_3_9_X:

- [x] /HICorePhysics/HIRun2010-PromptReco-v3/RECO			[19.3TB](https://cmsweb.cern.ch/phedex/prod/Data::Subscriptions#state=create_since%3D1586107202%3Bnode%3D2241%3Brequest%3D2232881) 	
- [x] /HIAllPhysics/HIRun2010-ZS-v2/RECO			[190.9TB](https://cmsweb.cern.ch/phedex/prod/Data::Subscriptions#state=create_since%3D1587312806%3Bnode%3D2241%3Brequest%3D2247252)	

### 2011 pp slc5, CMSSW_4_4_X :
- [x] /AllPhysics2760/Run2011A-16Jul2011-v1/RECO			                [6.6TB](https://cmsweb.cern.ch/phedex/prod/Data::Subscriptions#state=create_since%3D1587996682%3Bnode%3D2241%3Brequest%3D2254918)
- [x] /MinBias0Tesla0/Run2011A-PromptReco-v5/RECO				938.8GB
- [x] /MinBias0Tesla1/Run2011A-PromptReco-v5/RECO				930.3GB
- [x] /MinBias0Tesla2/Run2011A-PromptReco-v5/RECO			        938.7GB
tbc:
- [x] **/AllPhysics2760/Nov2011_HI-SD_JetHI-276TeV_ppRereco/RECO**		[275.1GB](https://cmsweb.cern.ch/phedex/prod/Data::Subscriptions#node=2241;reqfilter=2285910)
- [x] **/AllPhysics2760/Nov2011_HI-SD_MuHI-276TeV_ppRereco/RECO**		682.7GB
- [x] **/AllPhysics2760/Nov2011_HI-SD_PhotonHI-276TeV_ppRereco/RECO**	315.0GB
- [x] **/ForwardTriggers/HIRun2011-PromptReco-v1/RECO**			48.3GB

### 2011 PbPb slc5, CMSSW_3_9_X/CMSSW_4_4:
- [x] /HIDiMuon/HIRun2011-04Mar2013-v1/RECO				[3.2TB](https://cmsweb.cern.ch/phedex/prod/Data::Subscriptions#state=create_since%3D1581862159%3Bnode%3D2241%3Brequest%3D2142644)
- [x] /HIHighPt/HIRun2011-15Apr2013-v1/RECO					[1.6TB](https://cmsweb.cern.ch/phedex/prod/Data::Subscriptions#state=create_since%3D1579699605%3Bnode%3D2241%3Brequest%3D2114688)

- [x] /HIMinBiasUPC/HIRun2011-12Jun2013-v1/RECO				[11.6TB](https://cmsweb.cern.ch/phedex/prod/Data::Subscriptions#state=create_since%3D1586592590%3Bnode%3D2241%3Brequest%3D2238707)
- [x] /MinimumBias/HIRun2011-PromptReco-v1/RECO				[1.8TB](https://cmsweb.cern.ch/phedex/prod/Data::Subscriptions#state=create_since%3D1586592590%3Bnode%3D2241%3Brequest%3D2238707)

### 2011 pp slc6, CMSSW_5_3:
Corresponding AOD already released (or to be released), to be checked if enough
- [ ] /MinimumBias/Run2011A-12Oct2013-v1/RECO				36.0TB
- [ ] /MinimumBias/Run2011B-12Oct2013-v1/RECO				21.8TB

**Comment by katilp** [comment]
Note on the final destination on `/eos/opendata/cms/`:

With the same logic as pp data, i.e. open data files are in:
`root://eospublic.cern.ch//eos/opendata/cms/Run2011A/TauPlusX/AOD/12Oct2013-v1/10000/0013F0F9-3E43-E311-8D7F-FA163EBFD6C9.root`
and the CMS files (from DAS) in:
/store/data/Run2011A/TauPlusX/AOD/12Oct2013-v1/10001/FE343BC4-9944-E311-A093-FA163E08EE1F.root

i.e. **Run2011A** in this case is the top directory under `/eos/opendata/cms/`

For HI data, the CMS files are in
`/store/hidata/HIRun2011/HIHighPt/RECO/15Apr2013-v1/110000/E8931249-76B4-E211-A5CC-842B2B6F81CC.root`

i.e for these files a **HIRun2011** should be created under `/eos/opendata/cms/`

**Comment by tiborsimko** [comment]
Both datasets transferred, as discussed IRL into the `hidata` directory:

- `/eos/opendata/cms/hidata/HIRun2011/HIDiMuon`
- `/eos/opendata/cms/hidata/HIRun2011/HIHighPt`

**Comment by katilp** [comment]
Follow up for the two remaining MinBias RECO in #94
