### ISSUE TITLE
CMS - HI GT's

### ISSUE THREAD

**Issue by katilp** [cernopendata/data-curation#75]
(from #72 )

Define the GT needed for the analysis of the datasets in #73 and make them as sqlite files in /cvmfs/cms-opendata-conddb.cern.ch/ 
Start with the transferred dataset e.g. **/HIHighPt/HIRun2011-15Apr2013-v1/RECO**

(NB the Run1 GTs are available in https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideFrontierConditions?rev=609)

### 2010 PbPb slc5, CMSSW_3_9_X:

-  /HICorePhysics/HIRun2010-PromptReco-v3/RECO
  - 201 runs Minimum: 150844 Maximum: 153368			
-  /HIAllPhysics/HIRun2010-ZS-v2/RECO
  - 174 runs Minimum: 150436 Maximum: 153368					

### 2011 pp slc5, CMSSW_4_4_X :
-  /AllPhysics2760/Run2011A-16Jul2011-v1/RECO	
  - 49 runs Minimum: 161329 Maximum: 161484			
-  /MinBias0Tesla0/Run2011A-PromptReco-v5/RECO	
  - 21 runs Minimum: 169811 Maximum: 170044			
-  /MinBias0Tesla1/Run2011A-PromptReco-v5/RECO	
  - 21 runs Minimum: 169811 Maximum: 170044			
- /MinBias0Tesla2/Run2011A-PromptReco-v5/RECO
  - 21 runs Minimum: 169811 Maximum: 170044			
tbc:
- /AllPhysics2760/Nov2011_HI-SD_JetHI-276TeV_ppRereco/RECO	
  - 9 runs Minimum: 161366 Maximum: 161474
-  /AllPhysics2760/Nov2011_HI-SD_MuHI-276TeV_ppRereco/RECO	
  - 9 runs Minimum: 161366 Maximum: 161474
-  /AllPhysics2760/Nov2011_HI-SD_PhotonHI-276TeV_ppRereco/RECO	
  - 9 runs Minimum: 161366 Maximum: 161474
-  /ForwardTriggers/HIRun2011-PromptReco-v1/RECO
  - 724 runs Minimum: 181510 Maximum: 183337		

### 2011 PbPb slc5, CMSSW_3_9_X/CMSSW_4_4:
-  /HIDiMuon/HIRun2011-04Mar2013-v1/RECO		
   - 62 runs Minimum: 181611 Maximum: 183013				
-  /HIHighPt/HIRun2011-15Apr2013-v1/RECO		
  - 62 runs Minimum: 181611 Maximum: 183013		
-  /HIMinBiasUPC/HIRun2011-12Jun2013-v1/RECO   
  - 62 runs Minimum: 181611 Maximum: 183013	
-  /MinimumBias/HIRun2011-PromptReco-v1/RECO  -
  - 362 runs	Minimum: 181510 Maximum: 183337	

### 2011 pp slc6, CMSSW_5_3:
Corresponding AOD already released (or to be released), to be checked if enough
-  /MinimumBias/Run2011A-12Oct2013-v1/RECO			
-  /MinimumBias/Run2011B-12Oct2013-v1/RECO

**Comment by bylinkin** [comment]
Global Tags to be used for the analysis of these samples:
2010 PbPb slc5, CMSSW_3_9_X: **GR_R_39X_V6B** 
2011 pp slc5, CMSSW_4_4_X : **GR_R_44_V15**
2011 PbPb slc5, CMSSW_4_4: **GR_R_44_V15**
2011 pp slc6, CMSSW_5_3: **GR_R_53_V21A**

**Comment by katilp** [comment]
@ggovi Could you kindly export the GTs above with the respective CMSSW versions?
slc5 available in the VM (http://opendata.cern.ch/record/250, pls note its has two shells: the slc5 shell opens from a desktop icon "CMS Shell") or through the slc5 container from https://github.com/clelange/cmssw-docker/. 

Do you need the exact run ranges?

- [ ] upload the sqlite files corresponding to GTs under /cvmfs/cms-opendata-conddb.cern.ch
      Reminder for copying the files:
> You'd login to cvmfs-cms-opendata-conddb.cern.ch and then do
> 
>     sudo -i -u cvcmso
>     cvmfs_server transaction cms-opendata-conddb.cern.ch
> 
>     Now /cvmfs/cms-opendata-conddb.cern.ch is writable and you can use the
>     shell to copy all the files you need. Once finished, you'd do
> 
>     cvmfs_server publish cms-opendata-conddb.cern.ch
> 
>     And ~1h later the content appears at the clients.

- [ ] test the reading #76

**Comment by ggovi** [comment]
@katilp 
GR_R_44_V15 has been exported in /cvmfs/cms-opendata-conddb.cern.ch

Please let me know if there is any issue.

**Comment by ggovi** [comment]
@katilp 
GR_R_39X_V6B ready as well.

**Comment by katilp** [comment]
Thanks a lot @ggovi !
For the reading, should we set the two ln's as usual (http://opendata.cern.ch/docs/cms-guide-for-condition-database):
```
ln -sf /cvmfs/cms-opendata-conddb.cern.ch/[GTNAME] [GTNAME]
ln -sf /cvmfs/cms-opendata-conddb.cern.ch/[GTNAME].db [GTNAME].db
```

**Comment by katilp** [comment]
I've tested `GR_R_44_V15` with [this slc5-based trigger info code](https://github.com/cms-opendata-analyses/trigger_examples/tree/2010/TriggerInfo/TriggerInfoAnalyzer), and it looks OK, for at least that part of GT.

For the record, on the slc5 VM (CMS-OpenData-1.1.2) with

```
cmsrel CMSSW_4_4_7
cd CMSSW_4_4_7/src
cmsenv
git clone -b 2010 --no-checkout git://github.com/cms-opendata-analyses/trigger_examples.git
cd trigger_examples
git config core.sparseCheckout true
echo 'TriggerInfo/TriggerInfoAnalyzer' > .git/info/sparse-checkout
git checkout   
mv TriggerInfo ../.
cd ..
rm -rf trigger_examples   
cd TriggerInfo/TriggerInfoAnalyzer
scram b
ln -s python/triggerinfoanalyzer_cfg.py .

ln -sf /cvmfs/cms-opendata-conddb.cern.ch/GR_R_44_V15 GR_R_44_V15
ln -sf /cvmfs/cms-opendata-conddb.cern.ch/GR_R_44_V15.db GR_R_44_V15.db
```

Change the file name (`root://eospublic.cern.ch//eos/opendata/cms/hidata/HIRun2011/HIHighPt/RECO/15Apr2013-v1/110000/10EF1D2D-77B4-E211-A652-003048F1C494.root`), the Global Tag and the dataset name for the analyzer input  in the configuration file:

```
process.GlobalTag.connect = cms.string('sqlite_file:/cvmfs/cms-opendata-conddb.cern.ch/GR_R_44_V15.db')
process.GlobalTag.globaltag = 'GR_R_44_V15::All'
....
datasetName = cms.string("HIHighPt")

```
And run

`cmsRun triggerinfoanalyzer_cfg.py > trigger.log`

This produces runtime warnings, but they are the same as when I read the GT from the frontier, which I have tried on the slc5 singularity available from lxplus. To run on that slc5 shell (instead of VM), do the following on lxplus

```
cmssw-env --cmsos slc5
source /cvmfs/cms.cern.ch/cmsset_default.sh
```

and keep the reading from the frontier by commenting the sqlite line
`process.GlobalTag.connect = cms.string('sqlite_file:/cvmfs/cms-opendata-conddb.cern.ch/GR_R_44_V15.db')`

**Comment by katilp** [comment]
The available release area for CMSSW_39X are:

```
bash-3.2$ scram list CMSSW_3_9

Listing installed projects available for platform >> slc5_amd64_gcc434 <<

--------------------------------------------------------------------------------
| Project Name  | Project Version          | Project Location                  |
--------------------------------------------------------------------------------

  CMSSW           CMSSW_3_9_2_patch5
                                         --> /cvmfs/cms.cern.ch/slc5_amd64_gcc434/cms/cmssw-patch/CMSSW_3_9_2_patch5
  CMSSW           CMSSW_3_9_2_patch2
                                         --> /cvmfs/cms.cern.ch/slc5_amd64_gcc434/cms/cmssw-patch/CMSSW_3_9_2_patch2
  CMSSW           CMSSW_3_9_2
                                         --> /cvmfs/cms.cern.ch/slc5_amd64_gcc434/cms/cmssw/CMSSW_3_9_2

```
Use the most recent patch5?

**Comment by katilp** [comment]
Reading of both GT's `GR_R_44_V15` and `GR_R_39X_V6B` from `/cvmfs/cms-opendata-conddb.cern.ch` now tested to be OK (at the level of HLT trigger info reading) on a slc5 container, with CMSSW_4_4_7 and CMSSW_3_9_2_patch5, respectively
https://gitlab.cern.ch/kati/hi-test

**Comment by katilp** [comment]
Follow up for the two MinBias RECO files in #94
