### ISSUE TITLE
CMS: copy the missing config file

### ISSUE THREAD

**Issue by katilp** [cernopendata/data-curation#83]
(from #80)
Take the missing config file  `/cdaq/physics/Run2011/5e33/v1.4/HLT/V4`
from https://cernbox.cern.ch/index.php/s/sSXvtuTUNhf3fka
and add it to /eos/opendata/cms/configuration-files/2011

**Comment by tiborsimko** [comment]
Done.  (Using `.py` suffix as for the other ones.)
