### ISSUE TITLE
CMS: note on 2011RunB ZeroBias

### ISSUE THREAD

**Issue by katilp** [cernopendata/data-curation#87]
(From #64)

/ZeroBias/Run2011B-12Oct2013-v1/AOD has only [6 runs](https://cmsweb.cern.ch/das/request?instance=prod/global&input=run+dataset%3D%2FZeroBias%2FRun2011B-12Oct2013-v1%2FAOD) out of which 2 have some luminosity (178003, 178004), but these two runs are not in [the validated run list](http://opendata.cern.ch/record/1001)

It will not be included in the release.

For the record:

Luminosity check on lxplus (the exact CMSSW version does not matter)

```
cd CMSSW_10_6_10/src 
cmsenv
setenv PATH $HOME/.local/bin:/cvmfs/cms-bril.cern.ch/brilconda/bin:$PATH

brilcalc lumi -r 178004    

```
etc                                                   

`

**Comment by tiborsimko** [comment]
Thanks, I have removed it from the 2011 RunB dataset list.
